[doc]
name = "ie-assignmets"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"

[[output]]
name = "http"
type = "pdf"
shell_escape = true
preamble = ""
index = "http/main.tex"
postamble = ""
