[doc]
name = "ie-assignmets"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"

[[output]]
name = "http"
type = "pdf"
shell_escape = true
preamble = ""
index = "http/main.tex"
postamble = ""

[[output]]
name = "http-hands-on"
type = "pdf"
shell_escape = true
preamble = ""
index = "http-hands-on/main.tex"
postamble = ""

[[output]]
name = "backend-morpheus"
type = "pdf"
shell_escape = true
preamble = ""
index = "backend-morpheus/main.tex"
postamble = ""

[[output]]
name = "backend-http-monitor"
type = "pdf"
shell_escape = true
preamble = ""
index = "backend-http-monitor/main.tex"
postamble = ""
